### ISSUE TITLE
How does this work with a "real" SPA like angular or react

### ISSUE THREAD

**Issue by TorsteinRapp** [TorsteinRapp/BFF_Testing#1]

**Comment by petterhoel** [comment]
@TorsteinRapp  vet du hvorfor idserver sender meg tilbake til 'signin-oidc' etter jeg har logga meg inn. Er det vanlig? 
![image](https://user-images.githubusercontent.com/1263775/73124310-57df8000-3f9a-11ea-8d3a-b552a2a59567.png)

**Comment by petterhoel** [comment]
nm fant ut at dette er en property  som settes på idserversiden

**Comment by petterhoel** [comment]
Closed by #3
